---
- name: "install required packages"
  apt:
    name: python-docker

- name: "Get latest Docker image"
  docker_image:
    name: "collabora/code"
    force: "true"

- name: Start container
  docker_container:
    name: "collabora-online"
    image: "collabora/code"
    state: started
    restart_policy: always
    ports:
      - "{{ collabora_ports }}"
    env:
      domain: "{{ collabora_domains | mandatory }}"
    capabilities:
    - "MKNOD"

